// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyCentral.API.Models;

#nullable disable

namespace StudyCentral.API.Migrations
{
    [DbContext(typeof(StudyDbContext))]
    [Migration("20260607024117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Content = "Welcome to StudyCentral",
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8988),
                            Name = "Welcome Announcement"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccd"),
                            Content = "The group project will start next week.",
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaad"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8990),
                            Name = "Project Information"
                        },
                        new
                        {
                            Id = new Guid("cdcdcdcd-cdcd-cdcd-cdcd-cdcdcdcdcdcd"),
                            Content = "The final exam will take place in June.",
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8991),
                            Name = "Exam Information"
                        },
                        new
                        {
                            Id = new Guid("abababab-abab-abab-abab-abababababab"),
                            Content = "This announcement has an attached file.",
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8992),
                            Name = "Announcement with File"
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Name")
                        .IsUnique();

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(9022),
                            Deadline = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create a simple API",
                            Name = "Demo Assignment"
                        },
                        new
                        {
                            Id = new Guid("efefefef-efef-efef-efef-efefefefefef"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(9029),
                            Deadline = new DateTime(2026, 1, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Design and implement a relational database",
                            Name = "Database Assignment"
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8937),
                            Description = "StudyCentral demonstration course",
                            Name = "System Integration",
                            TeacherId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaad"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8940),
                            Description = "Course about relational databases",
                            Name = "Database Systems"
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Relationship.CourseStudent", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseStudent", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StudentId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StudentId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StudentId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StudentId = new Guid("99999999-9999-9999-9999-999999999999")
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.StudyFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("StudyFolderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudyFolderId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("UploadedById");

                    b.ToTable("StudyFiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56565656-5656-5656-5656-565656565656"),
                            AltText = "Course syllabus",
                            BlobName = "studycentral-testfile1.odt",
                            ContentType = "application/vnd.oasis.opendocument.text",
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(9078),
                            FileName = "studycentral-testfile1.odt",
                            FileType = 4,
                            Size = 9172L,
                            StudyFolderId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            UploadedById = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("67676767-6767-6767-6767-676767676767"),
                            AltText = "Week 1 lecture slides",
                            BlobName = "studycentral-testfile2.odt",
                            ContentType = "application/vnd.oasis.opendocument.text",
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(9086),
                            FileName = "studycentral-testfile2.odt",
                            FileType = 4,
                            Size = 9207L,
                            StudyFolderId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            UploadedById = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("78787878-7878-7878-7878-787878787878"),
                            AltText = "Announcement file",
                            AnnouncementId = new Guid("abababab-abab-abab-abab-abababababab"),
                            BlobName = "studycentral-testfile3.pdf",
                            ContentType = "application/pdf",
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(9089),
                            FileName = "studycentral-testfile3.pdf",
                            FileType = 3,
                            Size = 17797L,
                            UploadedById = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.StudyFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("StudyFolders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(9063),
                            Name = "Course Materials"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(9065),
                            Name = "Week 1",
                            ParentFolderId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("abababab-abab-abab-abab-abababababab"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(9066),
                            Name = "Assignments"
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Feedback")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("AssignmentId", "StudentId")
                        .IsUnique();

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            AssignmentId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Comment = "Demo submission",
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(9043),
                            Status = 1,
                            StudentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SubmittedAt = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            AssignmentId = new Guid("efefefef-efef-efef-efef-efefefefefef"),
                            Comment = "Test student submission 1",
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(9046),
                            Status = 1,
                            StudentId = new Guid("44444444-4444-4444-4444-444444444444"),
                            SubmittedAt = new DateTime(2026, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("13131313-1313-1313-1313-131313131313"),
                            AssignmentId = new Guid("efefefef-efef-efef-efef-efefefefefef"),
                            Comment = "Test student submission 2",
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(9047),
                            Grade = 1,
                            GradedAt = new DateTime(2026, 1, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3,
                            StudentId = new Guid("88888888-8888-8888-8888-888888888888"),
                            SubmittedAt = new DateTime(2026, 1, 3, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("14141414-1414-1414-1414-141414141414"),
                            AssignmentId = new Guid("efefefef-efef-efef-efef-efefefefefef"),
                            Comment = "Test student submission 3",
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(9050),
                            Grade = 4,
                            GradedAt = new DateTime(2026, 1, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = 4,
                            StudentId = new Guid("99999999-9999-9999-9999-999999999999"),
                            SubmittedAt = new DateTime(2026, 1, 5, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ProfilePictureId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProfilePictureId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8850),
                            Email = "admin@studycentral.dk",
                            FirstName = "Admin",
                            LastName = "User",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8854),
                            Email = "teacher@studycentral.dk",
                            FirstName = "Teacher",
                            LastName = "User",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8856),
                            Email = "teacher2@studycentral.dk",
                            FirstName = "Teacher2",
                            LastName = "User",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8857),
                            Email = "student@studycentral.dk",
                            FirstName = "Student",
                            LastName = "User",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8858),
                            Email = "teststudent@studycentral.dk",
                            FirstName = "Test",
                            LastName = "Student",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8859),
                            Email = "testteacher@studycentral.dk",
                            FirstName = "Test",
                            LastName = "Teacher",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8860),
                            Email = "teststudentwithoutcourse@studycentral.dk",
                            FirstName = "Test",
                            LastName = "StudentWithoutCourse",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8862),
                            Email = "testsubmissionstudent1@studycentral.dk",
                            FirstName = "Test",
                            LastName = "SubmissionStudent1",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2026, 6, 7, 2, 41, 17, 606, DateTimeKind.Utc).AddTicks(8863),
                            Email = "testsubmissionstudent2@studycentral.dk",
                            FirstName = "Test",
                            LastName = "SubmissionStudent2",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 0
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Announcement", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Course", "Course")
                        .WithMany("Announcements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Assignment", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Course", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.User", "Teacher")
                        .WithMany("TeachingCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Relationship.CourseStudent", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Course", "Course")
                        .WithMany("CourseStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyCentral.API.Models.Entities.User", "Student")
                        .WithMany("EnrolledCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.StudyFile", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Announcement", "Announcement")
                        .WithMany("StudyFiles")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudyCentral.API.Models.Entities.Assignment", "Assignment")
                        .WithMany("StudyFiles")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudyCentral.API.Models.Entities.StudyFolder", "StudyFolder")
                        .WithMany("StudyFiles")
                        .HasForeignKey("StudyFolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudyCentral.API.Models.Entities.Submission", "Submission")
                        .WithMany("StudyFiles")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudyCentral.API.Models.Entities.User", "UploadedBy")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Announcement");

                    b.Navigation("Assignment");

                    b.Navigation("StudyFolder");

                    b.Navigation("Submission");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.StudyFolder", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Course", "Course")
                        .WithMany("StudyFolders")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyCentral.API.Models.Entities.StudyFolder", "ParentFolder")
                        .WithMany("ChildFolders")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Submission", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyCentral.API.Models.Entities.User", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.User", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.StudyFile", "ProfilePicture")
                        .WithMany()
                        .HasForeignKey("ProfilePictureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProfilePicture");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Announcement", b =>
                {
                    b.Navigation("StudyFiles");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Assignment", b =>
                {
                    b.Navigation("StudyFiles");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Course", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Assignments");

                    b.Navigation("CourseStudents");

                    b.Navigation("StudyFolders");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.StudyFolder", b =>
                {
                    b.Navigation("ChildFolders");

                    b.Navigation("StudyFiles");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Submission", b =>
                {
                    b.Navigation("StudyFiles");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.User", b =>
                {
                    b.Navigation("EnrolledCourses");

                    b.Navigation("Submissions");

                    b.Navigation("TeachingCourses");

                    b.Navigation("UploadedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
