// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyCentral.API.Models;

#nullable disable

namespace StudyCentral.API.Migrations
{
    [DbContext(typeof(StudyDbContext))]
    [Migration("20260602184604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.Property<Guid>("EnrolledCoursesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StudentsId")
                        .HasColumnType("char(36)");

                    b.HasKey("EnrolledCoursesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("CourseUser");

                    b.HasData(
                        new
                        {
                            EnrolledCoursesId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StudentsId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            EnrolledCoursesId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StudentsId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            EnrolledCoursesId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StudentsId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            EnrolledCoursesId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            StudentsId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            EnrolledCoursesId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            StudentsId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            EnrolledCoursesId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            StudentsId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            EnrolledCoursesId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            StudentsId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            EnrolledCoursesId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            StudentsId = new Guid("88888888-8888-8888-8888-888888888888")
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Content = "Welcome to the course. Please review the syllabus and course materials.",
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4966),
                            CreatedById = new Guid("22222222-2222-2222-2222-222222222222"),
                            Title = "Welcome to Web Development",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Content = "The HTML Portfolio assignment is now available.",
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4968),
                            CreatedById = new Guid("22222222-2222-2222-2222-222222222222"),
                            Title = "First Assignment Released",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("33333333-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Content = "Project requirements and grading criteria have been uploaded.",
                            CourseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4969),
                            CreatedById = new Guid("22222222-2222-2222-2222-222222222222"),
                            Title = "Database Project Information",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("44444444-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Content = "Review SQL joins, normalization and indexing before the exam.",
                            CourseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4970),
                            CreatedById = new Guid("22222222-2222-2222-2222-222222222222"),
                            Title = "Exam Preparation",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("55555555-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Content = "Please install Docker Desktop before next week's exercises.",
                            CourseId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4972),
                            CreatedById = new Guid("33333333-3333-3333-3333-333333333333"),
                            Title = "Docker Setup Guide",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("66666666-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Content = "The Azure Blob Storage assignment is now available.",
                            CourseId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4972),
                            CreatedById = new Guid("33333333-3333-3333-3333-333333333333"),
                            Title = "Azure Assignment Released",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4996),
                            CreatedById = new Guid("22222222-2222-2222-2222-222222222222"),
                            Deadline = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create a personal portfolio website using HTML and CSS.",
                            Title = "HTML Portfolio"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(5000),
                            CreatedById = new Guid("22222222-2222-2222-2222-222222222222"),
                            Deadline = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Develop a RESTful API using ASP.NET Core.",
                            Title = "ASP.NET Web API"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            CourseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(5002),
                            CreatedById = new Guid("22222222-2222-2222-2222-222222222222"),
                            Deadline = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Design an ER diagram for the provided business case.",
                            Title = "ER Diagram Design"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-4444-4444-4444-444444444444"),
                            CourseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(5004),
                            CreatedById = new Guid("22222222-2222-2222-2222-222222222222"),
                            Deadline = new DateTime(2026, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Write SQL queries to solve the provided tasks.",
                            Title = "SQL Query Assignment"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-5555-5555-5555-555555555555"),
                            CourseId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(5005),
                            CreatedById = new Guid("33333333-3333-3333-3333-333333333333"),
                            Deadline = new DateTime(2026, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Containerize and deploy the application using Docker.",
                            Title = "Docker Deployment"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-6666-6666-6666-666666666666"),
                            CourseId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(5007),
                            CreatedById = new Guid("33333333-3333-3333-3333-333333333333"),
                            Deadline = new DateTime(2026, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Implement file upload and storage using Azure Blob Storage.",
                            Title = "Azure Blob Storage"
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4919),
                            Description = "Learn HTML, CSS, JavaScript and ASP.NET development.",
                            TeacherId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Title = "Web Development"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4922),
                            Description = "Learn relational databases, SQL and data modelling.",
                            TeacherId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Title = "Database Systems"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4924),
                            Description = "Learn APIs, Docker, Azure and distributed systems.",
                            TeacherId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Title = "System Integration"
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.StudyFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AltText")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("UploadedById");

                    b.HasIndex("UserId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Feedback")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("AssignmentId", "StudentId")
                        .IsUnique();

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-7777-7777-7777-777777777777"),
                            AssignmentId = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Comment = "My HTML portfolio submission.",
                            Feedback = "Excellent work.",
                            Grade = 95m,
                            StudentId = new Guid("44444444-4444-4444-4444-444444444444"),
                            SubmittedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(5024)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-8888-8888-8888-888888888888"),
                            AssignmentId = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Comment = "Portfolio assignment completed.",
                            Feedback = "Good structure and styling.",
                            Grade = 85m,
                            StudentId = new Guid("55555555-5555-5555-5555-555555555555"),
                            SubmittedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(5031)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-9999-9999-9999-999999999999"),
                            AssignmentId = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Comment = "My submission.",
                            StudentId = new Guid("66666666-6666-6666-6666-666666666666"),
                            SubmittedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(5033)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            AssignmentId = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            Comment = "ASP.NET API project.",
                            Feedback = "Well implemented API.",
                            Grade = 90m,
                            StudentId = new Guid("44444444-4444-4444-4444-444444444444"),
                            SubmittedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(5034)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            AssignmentId = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            Comment = "ER diagram attached.",
                            Feedback = "Good normalization.",
                            Grade = 88m,
                            StudentId = new Guid("77777777-7777-7777-7777-777777777777"),
                            SubmittedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(5035)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            AssignmentId = new Guid("aaaaaaaa-5555-5555-5555-555555555555"),
                            Comment = "Docker deployment completed.",
                            StudentId = new Guid("88888888-8888-8888-8888-888888888888"),
                            SubmittedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(5036)
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ProfilePictureId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProfilePictureId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4738),
                            Email = "admin@mail.com",
                            FirstName = "Mister",
                            LastName = "Admin",
                            PasswordHash = "$2a$11$ZZdlueio8rsj67q/d/ZiBe03uM1mX0Y9JfFjwcP/X0KSRiE5G4Ke6",
                            Role = 3,
                            UpdatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4740)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4746),
                            Email = "teacher1@mail.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$ZZdlueio8rsj67q/d/ZiBe03uM1mX0Y9JfFjwcP/X0KSRiE5G4Ke6",
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4746)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4774),
                            Email = "teacher2@mail.com",
                            FirstName = "Bob",
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$ZZdlueio8rsj67q/d/ZiBe03uM1mX0Y9JfFjwcP/X0KSRiE5G4Ke6",
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4774)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4776),
                            Email = "student1@mail.com",
                            FirstName = "Charlie",
                            LastName = "Brown",
                            PasswordHash = "$2a$11$ZZdlueio8rsj67q/d/ZiBe03uM1mX0Y9JfFjwcP/X0KSRiE5G4Ke6",
                            Role = 1,
                            UpdatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4777)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4778),
                            Email = "student2@mail.com",
                            FirstName = "David",
                            LastName = "Wilson",
                            PasswordHash = "$2a$11$ZZdlueio8rsj67q/d/ZiBe03uM1mX0Y9JfFjwcP/X0KSRiE5G4Ke6",
                            Role = 1,
                            UpdatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4778)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4780),
                            Email = "student3@mail.com",
                            FirstName = "Emma",
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$ZZdlueio8rsj67q/d/ZiBe03uM1mX0Y9JfFjwcP/X0KSRiE5G4Ke6",
                            Role = 1,
                            UpdatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4780)
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4781),
                            Email = "student4@mail.com",
                            FirstName = "Frank",
                            LastName = "Miller",
                            PasswordHash = "$2a$11$ZZdlueio8rsj67q/d/ZiBe03uM1mX0Y9JfFjwcP/X0KSRiE5G4Ke6",
                            Role = 1,
                            UpdatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4782)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4783),
                            Email = "student5@mail.com",
                            FirstName = "Grace",
                            LastName = "Taylor",
                            PasswordHash = "$2a$11$ZZdlueio8rsj67q/d/ZiBe03uM1mX0Y9JfFjwcP/X0KSRiE5G4Ke6",
                            Role = 1,
                            UpdatedAt = new DateTime(2026, 6, 2, 18, 46, 4, 74, DateTimeKind.Utc).AddTicks(4783)
                        });
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("EnrolledCoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyCentral.API.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Announcement", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Course", "Course")
                        .WithMany("Announcements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyCentral.API.Models.Entities.User", "CreatedBy")
                        .WithMany("CreatedAnnouncements")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Assignment", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyCentral.API.Models.Entities.User", "CreatedBy")
                        .WithMany("CreatedAssignments")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Course", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.User", "Teacher")
                        .WithMany("TeachingCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.StudyFile", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Assignment", "Assignment")
                        .WithMany("Files")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudyCentral.API.Models.Entities.Course", "Course")
                        .WithMany("Files")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudyCentral.API.Models.Entities.Submission", "Submission")
                        .WithMany("Files")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudyCentral.API.Models.Entities.User", "UploadedBy")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyCentral.API.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Assignment");

                    b.Navigation("Course");

                    b.Navigation("Submission");

                    b.Navigation("UploadedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Submission", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyCentral.API.Models.Entities.User", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.User", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.StudyFile", "ProfilePicture")
                        .WithMany()
                        .HasForeignKey("ProfilePictureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProfilePicture");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Assignment", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Course", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Assignments");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Submission", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.User", b =>
                {
                    b.Navigation("CreatedAnnouncements");

                    b.Navigation("CreatedAssignments");

                    b.Navigation("Submissions");

                    b.Navigation("TeachingCourses");

                    b.Navigation("UploadedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
