// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyCentral.API.Models;

#nullable disable

namespace StudyCentral.API.Migrations
{
    [DbContext(typeof(StudyDbContext))]
    partial class StudyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Content = "Welcome to StudyCentral",
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2634),
                            Name = "Welcome Announcement"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccd"),
                            Content = "The group project will start next week.",
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaad"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2636),
                            Name = "Project Information"
                        },
                        new
                        {
                            Id = new Guid("cdcdcdcd-cdcd-cdcd-cdcd-cdcdcdcdcdcd"),
                            Content = "The final exam will take place in June.",
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2637),
                            Name = "Exam Information"
                        },
                        new
                        {
                            Id = new Guid("abababab-abab-abab-abab-abababababab"),
                            Content = "This announcement has an attached file.",
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2638),
                            Name = "Announcement with File"
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Name")
                        .IsUnique();

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2694),
                            Deadline = new DateTime(2026, 6, 19, 21, 10, 29, 272, DateTimeKind.Utc).AddTicks(7260),
                            Description = "Create a simple API",
                            Name = "Demo Assignment"
                        },
                        new
                        {
                            Id = new Guid("efefefef-efef-efef-efef-efefefefefef"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2701),
                            Deadline = new DateTime(2026, 6, 27, 21, 10, 29, 272, DateTimeKind.Utc).AddTicks(7260),
                            Description = "Design and implement a relational database",
                            Name = "Database Assignment"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddabc"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2702),
                            Description = "Submit a proposal for your group project",
                            Name = "Project Proposal"
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16161616-1616-1616-1616-161616161616"),
                            ChatRoomId = new Guid("15151515-1515-1515-1515-151515151515"),
                            Content = "Welcome to the System Integration course chat.",
                            CreatedAt = new DateTime(2026, 6, 22, 21, 11, 29, 272, DateTimeKind.Utc).AddTicks(7260),
                            SenderId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("17171717-1717-1717-1717-171717171717"),
                            ChatRoomId = new Guid("15151515-1515-1515-1515-151515151515"),
                            Content = "Thanks. Is the first assignment already available?",
                            CreatedAt = new DateTime(2026, 6, 22, 21, 12, 29, 272, DateTimeKind.Utc).AddTicks(7260),
                            SenderId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("18181818-1818-1818-1818-181818181818"),
                            ChatRoomId = new Guid("15151515-1515-1515-1515-151515151515"),
                            Content = "Yes, you can find it under assignments.",
                            CreatedAt = new DateTime(2026, 6, 22, 21, 13, 29, 272, DateTimeKind.Utc).AddTicks(7260),
                            SenderId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("19191919-1919-1919-1919-191919191919"),
                            ChatRoomId = new Guid("15151515-1515-1515-1515-151515151515"),
                            Content = "Should we submit individually or as a group?",
                            CreatedAt = new DateTime(2026, 6, 22, 21, 14, 29, 272, DateTimeKind.Utc).AddTicks(7260),
                            SenderId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202020"),
                            ChatRoomId = new Guid("15151515-1515-1515-1515-151515151515"),
                            Content = "This one should be submitted individually.",
                            CreatedAt = new DateTime(2026, 6, 22, 21, 15, 29, 272, DateTimeKind.Utc).AddTicks(7260),
                            SenderId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Chat.ChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("ChatRooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15151515-1515-1515-1515-151515151515"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 272, DateTimeKind.Utc).AddTicks(7260),
                            Name = "System Integration Chat",
                            Type = 1
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Chat.ChatRoomMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "ChatRoomId");

                    b.HasIndex("ChatRoomId");

                    b.ToTable("ChatRoomMembers");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ChatRoomId = new Guid("15151515-1515-1515-1515-151515151515"),
                            JoinedAt = new DateTime(2026, 6, 22, 21, 10, 29, 272, DateTimeKind.Utc).AddTicks(7260)
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ChatRoomId = new Guid("15151515-1515-1515-1515-151515151515"),
                            JoinedAt = new DateTime(2026, 6, 22, 21, 10, 29, 272, DateTimeKind.Utc).AddTicks(7260)
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ChatRoomId = new Guid("15151515-1515-1515-1515-151515151515"),
                            JoinedAt = new DateTime(2026, 6, 22, 21, 10, 29, 272, DateTimeKind.Utc).AddTicks(7260)
                        },
                        new
                        {
                            UserId = new Guid("88888888-8888-8888-8888-888888888888"),
                            ChatRoomId = new Guid("15151515-1515-1515-1515-151515151515"),
                            JoinedAt = new DateTime(2026, 6, 22, 21, 10, 29, 272, DateTimeKind.Utc).AddTicks(7260)
                        },
                        new
                        {
                            UserId = new Guid("99999999-9999-9999-9999-999999999999"),
                            ChatRoomId = new Guid("15151515-1515-1515-1515-151515151515"),
                            JoinedAt = new DateTime(2026, 6, 22, 21, 10, 29, 272, DateTimeKind.Utc).AddTicks(7260)
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2604),
                            Description = "StudyCentral demonstration course",
                            Name = "System Integration",
                            TeacherId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaad"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2607),
                            Description = "Course about relational databases",
                            Name = "Database Systems"
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Relationship.CourseStudent", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseStudent", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StudentId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StudentId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StudentId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StudentId = new Guid("99999999-9999-9999-9999-999999999999")
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.StudyFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("StudyFolderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudyFolderId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("UploadedById");

                    b.ToTable("StudyFiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56565656-5656-5656-5656-565656565656"),
                            AltText = "Course syllabus",
                            BlobName = "studycentral-testfile1.odt",
                            ContentType = "application/vnd.oasis.opendocument.text",
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2752),
                            FileName = "studycentral-testfile1.odt",
                            FileType = 4,
                            Size = 9172L,
                            StudyFolderId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            UploadedById = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("67676767-6767-6767-6767-676767676767"),
                            AltText = "Week 1 lecture slides",
                            BlobName = "studycentral-testfile2.odt",
                            ContentType = "application/vnd.oasis.opendocument.text",
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2757),
                            FileName = "studycentral-testfile2.odt",
                            FileType = 4,
                            Size = 9207L,
                            StudyFolderId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            UploadedById = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("78787878-7878-7878-7878-787878787878"),
                            AltText = "Announcement file",
                            AnnouncementId = new Guid("abababab-abab-abab-abab-abababababab"),
                            BlobName = "studycentral-testfile3.pdf",
                            ContentType = "application/pdf",
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2758),
                            FileName = "studycentral-testfile3.pdf",
                            FileType = 3,
                            Size = 17797L,
                            UploadedById = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("89898989-8989-8989-8989-898989898989"),
                            AltText = "Submission 1 code",
                            BlobName = "studycentral-testfile4.odt",
                            ContentType = "application/vnd.oasis.opendocument.text",
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2760),
                            FileName = "studycentral-testfile4.odt",
                            FileType = 4,
                            Size = 204800L,
                            SubmissionId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            UploadedById = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("90909090-9090-9090-9090-909090909090"),
                            AltText = "Submission 2 code",
                            BlobName = "studycentral-testfile5.pdf",
                            ContentType = "application/pdf",
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2762),
                            FileName = "studycentral-testfile5.pdf",
                            FileType = 4,
                            Size = 409600L,
                            SubmissionId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            UploadedById = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.StudyFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("StudyFolders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2737),
                            Name = "Course Materials"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2739),
                            Name = "Week 1",
                            ParentFolderId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("abababab-abab-abab-abab-abababababab"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2740),
                            Name = "Assignments"
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Feedback")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("AssignmentId", "StudentId")
                        .IsUnique();

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            AssignmentId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Comment = "Demo submission",
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2715),
                            Status = 1,
                            StudentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SubmittedAt = new DateTime(2026, 6, 22, 21, 10, 29, 272, DateTimeKind.Utc).AddTicks(7260)
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            AssignmentId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Comment = "Test student submission 1",
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2719),
                            Status = 1,
                            StudentId = new Guid("44444444-4444-4444-4444-444444444444"),
                            SubmittedAt = new DateTime(2026, 6, 23, 21, 10, 29, 272, DateTimeKind.Utc).AddTicks(7260)
                        },
                        new
                        {
                            Id = new Guid("13131313-1313-1313-1313-131313131313"),
                            AssignmentId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Comment = "Test student submission 2",
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2720),
                            Grade = 1,
                            GradedAt = new DateTime(2026, 6, 25, 21, 10, 29, 272, DateTimeKind.Utc).AddTicks(7260),
                            Status = 3,
                            StudentId = new Guid("88888888-8888-8888-8888-888888888888"),
                            SubmittedAt = new DateTime(2026, 6, 24, 21, 10, 29, 272, DateTimeKind.Utc).AddTicks(7260)
                        },
                        new
                        {
                            Id = new Guid("14141414-1414-1414-1414-141414141414"),
                            AssignmentId = new Guid("efefefef-efef-efef-efef-efefefefefef"),
                            Comment = "Test student submission 3",
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2723),
                            Grade = 4,
                            GradedAt = new DateTime(2026, 6, 27, 21, 10, 29, 272, DateTimeKind.Utc).AddTicks(7260),
                            Status = 4,
                            StudentId = new Guid("99999999-9999-9999-9999-999999999999"),
                            SubmittedAt = new DateTime(2026, 6, 26, 21, 10, 29, 272, DateTimeKind.Utc).AddTicks(7260)
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ProfilePictureId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProfilePictureId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2477),
                            Email = "admin@studycentral.dk",
                            FirstName = "Admin",
                            LastName = "User",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2481),
                            Email = "teacher@studycentral.dk",
                            FirstName = "Teacher",
                            LastName = "User",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2482),
                            Email = "teacher2@studycentral.dk",
                            FirstName = "Teacher2",
                            LastName = "User",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2484),
                            Email = "student@studycentral.dk",
                            FirstName = "Student",
                            LastName = "User",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2485),
                            Email = "teststudent@studycentral.dk",
                            FirstName = "Test",
                            LastName = "Student",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2486),
                            Email = "testteacher@studycentral.dk",
                            FirstName = "Test",
                            LastName = "Teacher",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2487),
                            Email = "teststudentwithoutcourse@studycentral.dk",
                            FirstName = "Test",
                            LastName = "StudentWithoutCourse",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2488),
                            Email = "testsubmissionstudent1@studycentral.dk",
                            FirstName = "Test",
                            LastName = "SubmissionStudent1",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2026, 6, 22, 21, 10, 29, 447, DateTimeKind.Utc).AddTicks(2489),
                            Email = "testsubmissionstudent2@studycentral.dk",
                            FirstName = "Test",
                            LastName = "SubmissionStudent2",
                            PasswordHash = "$2a$11$ykLhMftf0qTgiJAxVTAt/eGyXwEKWocNpyC/a3wwOywH/XRNcK2e2",
                            Role = 0
                        });
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Announcement", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Course", "Course")
                        .WithMany("Announcements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Assignment", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Chat.ChatMessage", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Chat.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyCentral.API.Models.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Chat.ChatRoom", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Chat.ChatRoomMember", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Chat.ChatRoom", "ChatRoom")
                        .WithMany("Members")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyCentral.API.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Course", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.User", "Teacher")
                        .WithMany("TeachingCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Relationship.CourseStudent", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Course", "Course")
                        .WithMany("CourseStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyCentral.API.Models.Entities.User", "Student")
                        .WithMany("EnrolledCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.StudyFile", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Announcement", "Announcement")
                        .WithMany("StudyFiles")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudyCentral.API.Models.Entities.Assignment", "Assignment")
                        .WithMany("StudyFiles")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudyCentral.API.Models.Entities.StudyFolder", "StudyFolder")
                        .WithMany("StudyFiles")
                        .HasForeignKey("StudyFolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudyCentral.API.Models.Entities.Submission", "Submission")
                        .WithMany("StudyFiles")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudyCentral.API.Models.Entities.User", "UploadedBy")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Announcement");

                    b.Navigation("Assignment");

                    b.Navigation("StudyFolder");

                    b.Navigation("Submission");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.StudyFolder", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Course", "Course")
                        .WithMany("StudyFolders")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyCentral.API.Models.Entities.StudyFolder", "ParentFolder")
                        .WithMany("ChildFolders")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Submission", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyCentral.API.Models.Entities.User", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.User", b =>
                {
                    b.HasOne("StudyCentral.API.Models.Entities.StudyFile", "ProfilePicture")
                        .WithMany()
                        .HasForeignKey("ProfilePictureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProfilePicture");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Announcement", b =>
                {
                    b.Navigation("StudyFiles");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Assignment", b =>
                {
                    b.Navigation("StudyFiles");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Chat.ChatRoom", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Course", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Assignments");

                    b.Navigation("CourseStudents");

                    b.Navigation("StudyFolders");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.StudyFolder", b =>
                {
                    b.Navigation("ChildFolders");

                    b.Navigation("StudyFiles");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.Submission", b =>
                {
                    b.Navigation("StudyFiles");
                });

            modelBuilder.Entity("StudyCentral.API.Models.Entities.User", b =>
                {
                    b.Navigation("EnrolledCourses");

                    b.Navigation("Submissions");

                    b.Navigation("TeachingCourses");

                    b.Navigation("UploadedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
